---
title: "Biostatistics"
---

Welcome to the website of the course "Biostatistics" of the master's programme "Translational Neuroscience" of the Julius-Maximilians-University Würzburg.

Please use the navigation on the left to select the slides for each session (recommendation: Open in new tab).


| Date            | Topic                        | Reading            | Lecturer           | Project Deadlines              |
|-----------------|------------------------------|--------------------|--------------------|--------------------------------|
| 16.10.          | General & R Intro            | ST21: 1-3, QF: 1-3 | Reutter            | R & RStudio installed          |
| 23.10.          | Models                       | ST21: 4, QF: 4-6   | Hildebrandt        |                                |
| 30.10.          | Data Wrangling               | ST21: 4, QF: 4-6   | Reutter            |                                |
| 06.11.          | Data Visualization           | QF: 7              | Reutter            |                                |
| 13.11.          | Probability                  | ST21: 7-8, QF: 8   | Hildebrandt        | Dataset                        |
| 20.11.          | *Penance Day*                |                    |                    |                                |
| 27.11.          | Sampling                     | ST21: 7-8, QF: 8   | Hildebrandt        |                                |
| 04.12.          | Hypothesis Testing           | ST21: 9-10         | Reutter            |                                |
| 11.12.          | Comparing Means & Categories | ST21: 12, 15       | Reutter            | Research Question & Hypotheses |
| 18.12.          | Exercises (t-Tests, Chi²)    | ST21: 12, 15       | Reutter            |                                |
| 25.12. & 01.01. | *Christmas & New Year's*     |                    |                    |                                |
| 08.01.          | (General) Linear Models      | ST21: 12-13        | Hildebrandt        | First Analysis Ideas           |
| 15.01.          | Exercises (GLM)              | ST21: 12-13        | Hildebrandt        |                                |
| 22.01.          | Linear Mixed Models          | ST21: 14           | Hildebrandt        | Analysis (with R scripts)      |
| 29.01.          | R Markdown for Reports       |                    | Reutter            |                                |
| 05.02.          | Troubleshooting Your Report  |                    | both               | Send Questions via Email       |
| 12.02.          | ~~Reproducible Research~~    | ~~ST21: 18~~       | ~~Hildebrandt~~    | Report (with R Markdown)       |
