---
title: "Week 6: First Analysis"
subtitle: "Chi², t-test, correlation and one-way ANOVA"
author: "Lea"
date: "2022-11-20"
output: html_document
---

# Setup

## Install and load packages

```{r}
install.packages("car")
install.packages("effectsize")
install.packages("tidyverse")
install.packages("report")
install.packages("pwr")
install.packages("lsr")
install.packages("broom")
install.packages("afex")
install.packages("emmeans")
install.packages("performance")


library(car)
library(effectsize)
library(report)
library(pwr)
library(lsr)
library(broom)
library(afex)
library(emmeans)
library(performance)
library(tidyverse)

```



# Chi² test

Simulate data to use:  

```{r}
# get data into R:
lever_presses <- as.table(c(5,4,11))
dimnames(lever_presses) <- list(c("blue", "green", "red"))

lever_presses2 <- as.table(rbind(c(3, 12, 5), c(5, 4, 11)))
dimnames(lever_presses2) <- list(gender = c("Treatment", "Control"),
                    party = c("Blue","Green", "Red"))

```

[Add text and code chunks for analysis here!]  

# *t*-test

Simulate data

```{r}
sim_data_t <- tibble(
  group = rep(c("treatment", "control"), each=20),
  reaction_times = c(rnorm(20, 400, 100), rnorm(20, 450, 100))
)
```


# Paired-samples *t*-test

Download the data, save it in your class folder and load it into R with this code:  
```{r}
gaze <- read_csv("Mehr Song and Spelke 2016 Experiment 1.csv") %>%
  filter(exp1 == 1) %>%
  select(id,
         Baseline_Proportion_Gaze_to_Singer,
         Test_Proportion_Gaze_to_Singer) %>%
  rename(baseline = Baseline_Proportion_Gaze_to_Singer,
         test = Test_Proportion_Gaze_to_Singer)
```

# One-way ANOVA

Download data from MS Teams and save in class folder  
```{r}

dat0 <- read_csv("James Holmes_Expt 2_DATA.csv") # or wherever you saved file
```

