<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Mario Reutter (slides adapted from Dr.&nbsp;Lea Hildebrandt)">

<title>Biostatistics - 08 Modeling Relationships</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./W8_ModelingRelationships.html">08 Modeling Relationships</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W1_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01a Introduction to Biostatistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W1b_IntroR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01b Intro to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W2_Models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W3_DataWranglingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W4_DataVizR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 Data Visualization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W5_Sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05 Probabilities &amp; Sampling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W6_ProbabilityR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">06 Probability &amp; Sampling in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W7_Hypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07 Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W8_ModelingRelationships.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">08 Modeling Relationships</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W9_FirstAnalysisR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">09 Statistical Analyses in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W10_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10 The General Linear Model &amp; Multivariate Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W11_GLMinR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11 ANOVA &amp; the General Linear Model in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W12_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12 Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W13_RMarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13 R Markdown</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W15_RepResearchR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15 Reproducible Research</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="W8_ModelingRelationships.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">08 Modeling Relationships</h1>
<p class="subtitle lead"></p><div class="line-block">Julius-Maximilians-University Würzburg<br>
Course: “Biostatistics”<br>
Translational Neuroscience</div><p></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Mario Reutter (slides adapted from Dr.&nbsp;Lea Hildebrandt) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="modeling-categorical-relationships" class="level1">
<h1>Modeling <em>Categorical</em> Relationships</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode css code-with-copy"><code class="sourceCode css"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>code<span class="fu">.sourceCode</span> {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="kw">font-size</span><span class="ch">:</span> <span class="dv">1.4</span><span class="dt">em</span><span class="op">;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>div<span class="fu">.cell-output-stdout</span> {</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="kw">font-size</span><span class="ch">:</span> <span class="dv">1.4</span><span class="dt">em</span><span class="op">;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<style type="text/css">
code.sourceCode {
  font-size: 1.4em;
}

div.cell-output-stdout {
  font-size: 1.4em;
}
</style>
</div>
<div class="cell" data-messages="false">
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'sfsmisc'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:dplyr':

    last</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'cowplot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:patchwork':

    align_plots</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:lubridate':

    stamp</code></pre>
</div>
</div>
<div class="notes">
<p>Now that we have covered the basics, we will apply them and turn to the question how to model particular relationships.</p>
</div>
<section id="chi²-test-general" class="level2">
<h2 class="anchored" data-anchor-id="chi²-test-general">Chi² Test: General</h2>
<p>We will first focus on modeling <em>categorical</em> relationships (of variables that are qualitative!).</p>
<p>. . .</p>
<p>These data are usually expressed in terms of <strong>counts</strong>.</p>
<p>. . .</p>
<p><strong>Example: Candy colors</strong></p>
<p>Bag of candy: 30 chocolates, 33 licorices, and 37 gumballs.</p>
<p>. . .</p>
<p>Is the distribution fair (i.e., 1/3rd of the bag = each candy) and the fact that there are only 30 chocolates a random accident?</p>
<p>. . .</p>
<p><strong>What is the likelihood that the count would come out this way (or even more extreme) if the true probability of each candy type is the same?</strong></p>
<div class="notes">
<p>Counts: For each combination of variables, how many observations do we have?</p>
<p>If the machine really sorts on average 1/3 of each in each bag? How much is due to chance?</p>
</div>
</section>
<section id="chi²-test-one-variable" class="level2">
<h2 class="anchored" data-anchor-id="chi²-test-one-variable">Chi² Test: One Variable</h2>
<p>The Chi² test checks whether observed counts differ from expected values (<span class="math inline">\(H_0\)</span>).</p>
<p><span class="math display">\[
\chi^2 = \sum_i\frac{(observed_i - expected_i)^2}{expected_i}
\]</span></p>
<p>. . .</p>
<p>The null hypothesis in our example is that the proportion of each type of candy is equal (1/3 or ~33.33).</p>
<p>If we plug in our values from above, we would calculate <span class="math inline">\(\chi^2\)</span> like this:</p>
<p><span class="math display">\[ \chi^2 = \frac{(30 - 33.33)^2}{33.33} + \frac{(33 - 33.33)^2}{33.33} + \frac{(37 - 33.33)^2}{33.33} = 0.74 \]</span></p>
<div class="notes">
<p>take the difference between observed and expected (33.33), square it, divide it by expected 33.33 and add everything up</p>
</div>
</section>
<section id="chi²-test-general-2" class="level2">
<h2 class="anchored" data-anchor-id="chi²-test-general-2">Chi² Test: General 2</h2>
<p>On its own, the <span class="math inline">\(\chi^2\)</span> statistic is not interpretable - it depends on its distribution.</p>
<p>The shape of the chi-squared distribution depends on the <em>degrees of freedom</em> (much like the <em>t</em> distribution), which is the number of category levels <span class="math inline">\(k-1\)</span>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2
3.5.0.
ℹ Please use the `legend.position.inside` argument of `theme()` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W8_ModelingRelationships_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>For the candy example, we use a chi-squared distribution with DFs = 2 (3 candy categories minus one). If we’d look at the distribution and found <span class="math inline">\(\chi^2 = .74\)</span> on the x-axis, we would see that it does not fall far into the tail of the distribution but is rather in the middle. If we calculate the <em>p</em>-value, we’d get <span class="math inline">\(P(\chi^2 &gt; .74) = 0.691\)</span>.</p>
<p>It is thus not particularly surprising to find this distribution of candies and we would not reject <span class="math inline">\(H_0\)</span> (equal proportions).</p>
</section>
<section id="contingency-tables-and-the-two-way-test" class="level2">
<h2 class="anchored" data-anchor-id="contingency-tables-and-the-two-way-test">Contingency Tables and the Two-Way Test</h2>
<p>The <span class="math inline">\(\chi^2\)</span> test is also used to test whether two categorical variables are related to each other.</p>
<p>. . .</p>
<p>Example: Are Black drivers more likely to be pulled over by police than white drivers?</p>
<p>We have two variables: Skin color (black vs white) and being pulled over (true vs.&nbsp;false). We can represent the data in a <em>contingency table</em> (remember: the <code>count()</code> function was helpful to do this in R):</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Contingency table for police search data</caption>
<thead>
<tr class="header">
<th style="text-align: left;">searched</th>
<th style="text-align: right;">Black</th>
<th style="text-align: right;">White</th>
<th style="text-align: right;">Black (relative)</th>
<th style="text-align: right;">White (relative)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">36244</td>
<td style="text-align: right;">239241</td>
<td style="text-align: right;">0.1295298</td>
<td style="text-align: right;">0.8550062</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">1219</td>
<td style="text-align: right;">3108</td>
<td style="text-align: right;">0.0043565</td>
<td style="text-align: right;">0.0111075</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>. . .</p>
<p>If there is no relationship between skin color and being searched, the frequencies of searches would be proportional to the frequencies of skin color. This would be our expected values. We can determine them using probabilities:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Black</th>
<th>White</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Not searched</strong></td>
<td><span class="math inline">\(P(\neg S)*P(B)\)</span></td>
<td><span class="math inline">\(P(\neg S)*P(W)\)</span></td>
<td><span class="math inline">\(P(\neg S)\)</span></td>
</tr>
<tr class="even">
<td><strong>Searched</strong></td>
<td><span class="math inline">\(P(S)*P(B)\)</span></td>
<td><span class="math inline">\(P(S)*P(W)\)</span></td>
<td><span class="math inline">\(P(S)\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(P(B)\)</span></td>
<td><span class="math inline">\(P(W)\)</span></td>
<td><span class="math inline">\(100\%\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Remember</strong>: You can only multiply two probabilities to get their conjoint probability if they are independent. Here, we <em>assume</em> independence to calculate expected values and then check how much our observed values <em>deviate</em> from independence.</p>
<div class="notes">
<p>Probabilities: Because we expect the variables to be <em>unrelated</em>, we can calculate the <strong>joint probability</strong> as the product of the <strong>marginal probabilities</strong>:<br>
<span class="math inline">\(P(X \cap Y) = P(X) * P(Y)\)</span></p>
<p>Marginal probabilities are the prob of each event occuring regardless of other events (in the margins of the table!)</p>
</div>
</section>
<section id="chi²-test-two-variables" class="level2">
<h2 class="anchored" data-anchor-id="chi²-test-two-variables">Chi² Test: Two Variables</h2>
<p>If we compute the standardized squared difference between observed and expected values, we can sum them up to get <span class="math inline">\(\chi^2 = 828.3\)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Contingency table for police search data</caption>
<thead>
<tr class="header">
<th style="text-align: left;">searched</th>
<th style="text-align: left;">driver_race</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">expected</th>
<th style="text-align: right;">stdSqDiff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Black</td>
<td style="text-align: right;">36244</td>
<td style="text-align: right;">36883.67</td>
<td style="text-align: right;">11.09</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Black</td>
<td style="text-align: right;">1219</td>
<td style="text-align: right;">579.33</td>
<td style="text-align: right;">706.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">239241</td>
<td style="text-align: right;">238601.33</td>
<td style="text-align: right;">1.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">3108</td>
<td style="text-align: right;">3747.67</td>
<td style="text-align: right;">109.18</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can then compute the <em>p</em>-value using a chi-squared distribution with <span class="math inline">\(DF = (levels_{var1} - 1) * (levels_{var2} - 1) = (2-1) * (2-1) = 1\)</span></p>
<p>We can also calculate a <span class="math inline">\(\chi^2\)</span> test easily in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(summaryDf2wayTable, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  summaryDf2wayTable
X-squared = 828.3, df = 1, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results indicate that the data are highly unlikely if there was no true relationship between skin color and police searches! We would thus reject <span class="math inline">\(H_0\)</span>.</p>
<p>Question: What is the direction of the observed relationship?</p>
<div class="notes">
<p>DF: computing the expected frequencies requires three values: total number of observations and marg probs each variable. thus only one of the four values can vary freely.</p>
</div>
</section>
<section id="standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals">Standardized Residuals</h2>
<p>If we want to know not only whether but also <em>how</em> the data differ from what we would expect under <span class="math inline">\(H_0\)</span>, we can examine the <strong>residuals</strong> of the model.</p>
<p>The residuals tell us for each cell how much the observed data deviates from the expected data.</p>
<p>To make the residuals better comparable, we will look at the <em>standardized</em> residuals:</p>
<p><span class="math display">\[
\text{standardized residual}_{ij} = \frac{observed_{ij} - expected_{ij}}{\sqrt{expected_{ij}}}
\]</span></p>
<p>where <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> are the rows and columns respectively.</p>
<p>. . .</p>
<p><strong>Negative residuals</strong> indicate an observed value <strong>smaller</strong> than expected.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of standardized residuals for police stop data</caption>
<thead>
<tr class="header">
<th style="text-align: left;">searched</th>
<th style="text-align: left;">driver_race</th>
<th style="text-align: right;">Standardized residuals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">Black</td>
<td style="text-align: right;">-3.330746</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">Black</td>
<td style="text-align: right;">26.576456</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">1.309550</td>
</tr>
<tr class="even">
<td style="text-align: left;">TRUE</td>
<td style="text-align: left;">White</td>
<td style="text-align: right;">-10.449072</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="notes">
<p>raw residuals depend on number of observations!</p>
<p>Black individuals are searched way more often than expected –&gt; helps us intepret significant results.</p>
</div>
</section>
<section id="odds-ratios" class="level2">
<h2 class="anchored" data-anchor-id="odds-ratios">Odds Ratios</h2>
<p>Alternatively, we can represent the relative likelihood of different outcomes as odds ratios:</p>
<p><span class="math display">\[
odds_{searched|black} = \frac{N(searched\cap black)}{N(\neg searched \cap black)} = \frac{1219}{36244} = 0.034
\]</span></p>
<p><span class="math display">\[
odds_{searched|white} = \frac{N(searched \cap white)}{N(\neg searched \cap white)} = \frac{3108}{239241} = 0.013
\]</span></p>
<p><span class="math display">\[
odds\ ratio = \frac{odds(searched|black)}{odds(searched|white)} = 2.59
\]</span></p>
<p>The odds of being searched are 2.59x higher for Black vs.&nbsp;white drivers!</p>
</section>
<section id="simpsons-paradox" class="level2">
<h2 class="anchored" data-anchor-id="simpsons-paradox">Simpson’s Paradox</h2>
<p>The Simpson’s Paradox is a great example of misleading summaries.</p>
<p>If we look at the baseball data below, we see that David Justice has a better batting average in every single year, but Derek Jeter has a better overall batting average:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Player</th>
<th>1995</th>
<th></th>
<th>1996</th>
<th></th>
<th>1997</th>
<th></th>
<th>Combined</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D. Jeter</td>
<td>12/48</td>
<td>.250</td>
<td>183/582</td>
<td>.314</td>
<td>190/654</td>
<td>.291</td>
<td>385/1284</td>
<td><strong>.300</strong></td>
</tr>
<tr class="even">
<td>D. Justice</td>
<td>104/411</td>
<td><strong>.253</strong></td>
<td>45/140</td>
<td><strong>.321</strong></td>
<td>163/495</td>
<td><strong>.329</strong></td>
<td>312/1046</td>
<td>.298</td>
</tr>
</tbody>
</table>
<p>How can this be?</p>
<p>. . .</p>
<p><strong>Simpson’s Paradox</strong>: A pattern is present in the combined dataset but may be different in subsets of the data.</p>
<p>. . .</p>
<p>Happens if another (lurking) variable changes across subsets (e.g., the number of at-bats, i.e., the denominator).</p>
<div class="notes">
<p>batting average: hits/at bats</p>
<p>1995: in general low batting averages, Justice a lot of at-bats =&gt; diminishes total combined value more strongly than for Jeter.</p>
</div>
</section>
<section id="simpsons-paradox-more-intuitive" class="level2">
<h2 class="anchored" data-anchor-id="simpsons-paradox-more-intuitive">Simpson’s Paradox: More intuitive</h2>
<p>While typing on a keyboard, what is the relationship between speed and accuracy (or typing errors)?<br>
(positive, negative, or none)</p>
<p>. . .</p>
<p><br>
</p>
<p>If I try to type faster, I will make more errors =&gt; speed-accuracy trade-off (negative association)</p>
<p>People who are better at typing usually are both faster and make fewer mistakes (positive association)</p>
<p>. . .</p>
<p><br>
</p>
<p>Answer: It depends</p>
<ul>
<li><strong>Within a person</strong>, the relationship between speed and accuracy is negative. My own skill is limited, I can either use it for speed or accuracy.</li>
<li><strong>Between persons</strong>, the relationship is positive due to inter-individual differences in overall typing skill.</li>
</ul>
<div class="notes">
<p>Usually, when leveling up, people don’t put all their skill points in only speed or accuracy.</p>
</div>
</section>
</section>
<section id="modeling-continuous-relationships" class="level1">
<h1>Modeling <em>Continuous</em> Relationships</h1>
<section id="example-income-inequality-and-hate-crimes" class="level2">
<h2 class="anchored" data-anchor-id="example-income-inequality-and-hate-crimes">Example: Income Inequality and Hate Crimes</h2>
<p>We want to look at a dataset that was used for an analysis of the relationship between income inequality (<em>Gini index</em>) and the prevalence of hate crimes in the USA.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W8_ModelingRelationships_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It looks like there is a positive relationship between the variables. How can we quantify this relationship?</p>
</section>
<section id="covariance-and-correlation" class="level2">
<h2 class="anchored" data-anchor-id="covariance-and-correlation">Covariance and Correlation</h2>
<p><strong>Covariance</strong>: How much do two variables <em>co-vary</em> with each other?</p>
<p>Variance (single variable): <span class="math inline">\(s^2 = \frac{\sum_{i=1}^n (x_i - \bar{x})^2}{N - 1}\)</span></p>
<p>Covariance (two variables): <span class="math inline">\(covariance = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{N - 1}\)</span></p>
<p>(Side note: Variance is the covariance of a variable with itself.)</p>
<p>. . .</p>
<p><br>
</p>
<p>“Is there a relation between the deviations of two different variables (from their means) across observations?”</p>
<p>. . .</p>
<p>Will be far from 0 if data points share a relationship. Positive values for same direction, negative values for opposite directions.</p>
<p>. . .</p>
<p>Covariance varies with overall level of variance in the data, so not that useful to describe relationships in general.</p>
<p>. . .</p>
<p><br>
</p>
<p><strong>Correlation coefficient</strong> (Pearson correlation): Scales the covariance by the standard deviations of the two variables and thus standardizes it (=&gt; <span class="math inline">\(r\)</span> varies between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span> =&gt; comparability!)</p>
<p><span class="math display">\[
r = \frac{covariance}{s_xs_y} = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{(N - 1)s_x s_y}
\]</span></p>
<div class="notes">
<p>Covariance depends on dataset!</p>
</div>
</section>
<section id="hypothesis-testing-for-correlations" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-for-correlations">Hypothesis Testing for Correlations</h2>
<p>The correlation between income inequality and hate crimes is <span class="math inline">\(r = .42\)</span>, which seems to be a reasonably strong (positive) relationship.</p>
<p>. . .</p>
<p>We can test whether such a relationship could occur by chance, even if there is actually no relationship. In this case, our null hypothesis is <span class="math inline">\(H_0: r = 0\)</span>.</p>
<p>. . .</p>
<p>To test whether there is a significant relationship, we can transform the <span class="math inline">\(r\)</span> statistic into a <span class="math inline">\(t\)</span> statistic:</p>
<p><span class="math display">\[
t_r = \frac{r\sqrt{N-2}}{\sqrt{1-r^2}}
\]</span></p>
<p>We can compute this easily in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform correlation test on hate crime data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  hateCrimes<span class="sc">$</span>avg_hatecrimes_per_100k_fbi,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  hateCrimes<span class="sc">$</span>gini_index</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  hateCrimes$avg_hatecrimes_per_100k_fbi and hateCrimes$gini_index
t = 3.2182, df = 48, p-value = 0.002314
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1619097 0.6261922
sample estimates:
      cor 
0.4212719 </code></pre>
</div>
</div>
<p>The <em>p</em>-value is quite small, which indicates that it is quite unlikely to find an <span class="math inline">\(r\)</span> value this high or more extreme. We would thus reject <span class="math inline">\(H_0: r = 0\)</span>.</p>
<p>Side note: There are more beautiful / convenient ways to do this in R. We will cover this in the next session.</p>
<div class="notes">
<p>subsetting with $!</p>
</div>
</section>
<section id="robust-correlations" class="level2">
<h2 class="anchored" data-anchor-id="robust-correlations">Robust Correlations</h2>
<p>In the plot, we have seen an <strong>outlier</strong>: The District of Columbia was quite different from the other data points.</p>
<p>. . .</p>
<p>The Pearson’s correlation coefficient <span class="math inline">\(r\)</span> is highly sensitive to outliers, see this hypothetical example:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W8_ModelingRelationships_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="robust-correlation-2" class="level2">
<h2 class="anchored" data-anchor-id="robust-correlation-2">Robust Correlation 2</h2>
<p>We can use a different correlation coefficient, though, which is less sensitive to outliers: <strong>Spearman correlation</strong>.</p>
<p>It is based on ranking (i.e., ordering) the data and using the ranks (instead of the original data) for the correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(hateCrimes<span class="sc">$</span>avg_hatecrimes_per_100k_fbi,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  hateCrimes<span class="sc">$</span>gini_index,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(hateCrimes$avg_hatecrimes_per_100k_fbi,
hateCrimes$gini_index, : Kann exakten p-Wert bei Bindungen nicht berechnen</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  hateCrimes$avg_hatecrimes_per_100k_fbi and hateCrimes$gini_index
S = 20146, p-value = 0.8221
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.03261836 </code></pre>
</div>
</div>
<p>The correlation has now dropped from <span class="math inline">\(.42\)</span> to <span class="math inline">\(.03\)</span> and is no longer significant. The influence of the one outlier has been greatly diminished.</p>
<p>Of course, a ranked correlation can also obscure true effects that critically depend on the scale of the data. When in doubt, try both and discuss reasons for differences.</p>
<div class="notes">
<p>Without outlier: perfectly <em>negative</em> correlation, with outlier: highly positive!</p>
</div>
</section>
<section id="correlation-and-causation" class="level2">
<h2 class="anchored" data-anchor-id="correlation-and-causation">Correlation and Causation</h2>
<p>Doing a well controlled, randomized experiment (RCT) is extremely helpful to gather causal evidence.</p>
<p>However, it is not always possible or ethical to do an experiment!</p>
<p>We can still collect (observational) data. However, if we correlate two variables, we <em>can’t</em> conclude that one causes the other: They <em>might</em> be related but there could also be a third variable that causes both (or even more complex causal structures).</p>
<p>. . .</p>
<p>If we have observational data, <strong>causal graphs</strong> can be helpful for interpreting causality:</p>
<div class="columns">
<div class="column">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/dag_latent_example.png" class="img-fluid figure-img" width="250"></p>
</figure>
</div>
</div>
</div>
</div><div class="column">
<p><em>Circle</em>: observed variables<br>
<em>rectangle</em>: latent (unobservable) variable<br>
</p>
<p><em>Green arrow</em>: positive relationship,<br>
<em>red</em>: negative</p>
<p><em>ExamGrade</em> and <em>FinishTime</em> seem negatively related if we ignore other variables!<br>
(“Hand in your exam early to improve your grade!”)</p>
<p><em>Knowledge</em> = theoretical mediator<br>
<em>StudyTime</em> = proxy for knowledge</p>
<p>If we control for StudyTime (which approximates individual knowledge), we find out that ExamGrade and FinishTime are (causally) unrelated!</p>
</div>
</div>
<div class="notes">
<p>We have briefly talked about <em>causation</em> in week 1</p>
<p>Think of data/questions where it is impossible/unethical!<br>
abused children and brain development!<br>
(3rd var: family stress -&gt; less intellectual engagement –&gt; poorer brain dev)</p>
<p>Correlation: s.th. is probably causing s.th. else but not clear what causes what!</p>
<p>DAG:<br>
green: pos, red: net<br>
circle: observed, rect: latent (unobservable)<br>
ExamGrade and FinishTime seem neg related if we ignore others<br>
knowledge = mediates<br>
StudyTime = proxy for knowledge, if we “control” it/hold it constant/only use people with same amount, we would see that EG and FT are unrelated!</p>
</div>
</section>
</section>
<section id="comparing-means-group-differences" class="level1 page-columns page-full">
<h1>Comparing Means (Group Differences)</h1>
<section id="testing-a-single-mean-one-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="testing-a-single-mean-one-sample-t-test">Testing a Single Mean (One sample <em>t</em>-Test)</h2>
<p>We sometimes might want to know whether a single value, the mean of a group, differs from a specific value, e.g.&nbsp;whether the blood pressure in the sample differs from or is bigger than 80.</p>
<p>. . .</p>
<p>We can test this using the <span class="math inline">\(t\)</span>-test, which we have already encountered in the “Hypothesis Testing” session!</p>
<p><span class="math display">\[
t = \frac{\hat{X} - \mu}{SEM}
\]</span></p>
<p><span class="math display">\[
SEM = \frac{\hat{\sigma}}{\sqrt{n}}
\]</span></p>
<p><span class="math inline">\(\hat{X}\)</span> is the mean of our sample, <span class="math inline">\(\mu\)</span> the hypothesized population mean (e.g.&nbsp;the value we want to test against, such as 80 for the blood pressure example).</p>
<p>We can easily calculate the <span class="math inline">\(t\)</span>-test in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x=</span>NHANES_adult<span class="sc">$</span>BPDiaAve, <span class="at">mu=</span><span class="dv">80</span>, <span class="at">alternative=</span><span class="st">'greater'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  NHANES_adult$BPDiaAve
t = -55.23, df = 4599, p-value = 1
alternative hypothesis: true mean is greater than 80
95 percent confidence interval:
 69.1588     Inf
sample estimates:
mean of x 
 69.47239 </code></pre>
</div>
</div>
<div class="notes">
<p>(The <span class="math inline">\(t\)</span> statistic thus asks how large the deviation of sample mean from the expected value with respect to the sampling variability of the mean!)</p>
<p>We tested the one-sided alternative (&gt;) and the blood pressure in the sample is much lower than 80, so it is far from significance</p>
<p>We can’t interpret the <span class="math inline">\(p\)</span>-value as evidence in favor of <span class="math inline">\(H_0\)</span> (i.e.&nbsp;larger <span class="math inline">\(p\)</span>-value! vs non.sign) –&gt; Bayes!</p>
</div>
</section>
<section id="comparing-two-means-two-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="comparing-two-means-two-sample-t-test">Comparing Two Means (Two sample <em>t</em>-Test)</h2>
<p>More often, we want to know whether there is a difference between the means of <em>two groups</em>.</p>
<p>Example: Do regular marijuana smokers watch more television?<br>
In this example, we expect that they watch <em>more</em> TV, which leads us to the following directional hypotheses:</p>
<p><span class="math inline">\(H_0\)</span> = marijuana smokers watch less or equally often TV,<br>
<span class="math inline">\(H_A\)</span> = marijuana smokers watch more TV.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456</span>) </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># drop duplicated IDs within the NHANES dataset</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>NHANES <span class="ot">&lt;-</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  NHANES <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">distinct</span>(ID,<span class="at">.keep_all=</span><span class="cn">TRUE</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>NHANES_adult <span class="ot">&lt;-</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  NHANES <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(Age<span class="sc">&gt;=</span><span class="dv">18</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(BMI)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># create sample with tv watching and marijuana use</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>NHANES_sample <span class="ot">&lt;-</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  NHANES_adult <span class="sc">%&gt;%</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(TVHrsDay, RegularMarij) <span class="sc">%&gt;%</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">TVHrsNum =</span> <span class="fu">recode</span>( <span class="co">#recode character values into numerical values</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>      TVHrsDay,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">"More_4_hr"</span> <span class="ot">=</span> <span class="dv">5</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">"4_hr"</span> <span class="ot">=</span> <span class="dv">4</span>, </span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>      <span class="st">"2_hr"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>      <span class="st">"1_hr"</span> <span class="ot">=</span> <span class="dv">1</span>, </span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>      <span class="st">"3_hr"</span> <span class="ot">=</span> <span class="dv">3</span>, </span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>      <span class="st">"0_to_1_hr"</span> <span class="ot">=</span> <span class="fl">0.5</span>,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>      <span class="st">"0_hrs"</span> <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">200</span>)</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(NHANES_sample,<span class="fu">aes</span>(RegularMarij,TVHrsNum)) <span class="sc">+</span></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">draw_quantiles=</span>.<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Regular marijuana user"</span>,</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"TV hours per day"</span></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W8_ModelingRelationships_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If the observations are independent (i.e.&nbsp;you really have two unrelated groups), you can use a very similar formula to calculate the <span class="math inline">\(t\)</span> statistic:</p>
<p><span class="math display">\[
t = \frac{\bar{X_1} - \bar{X_2}}{\sqrt{\frac{S_1^2}{n_1} + \frac{S_2^2}{n_2}}}
\]</span></p>
<p>whereby <span class="math inline">\(\hat{X_1}\)</span> and <span class="math inline">\(\hat{X_2}\)</span> are the group means, <span class="math inline">\(S_1^2\)</span> and <span class="math inline">\(S_2^2\)</span> the group variances, and <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> the group sizes.</p>
<p>Here are the results from a one-tailed <span class="math inline">\(t\)</span>-test in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">t.test</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  TVHrsNum <span class="sc">~</span> RegularMarij,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> NHANES_sample,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="st">'less'</span> <span class="co"># because of coding of the groups!</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  TVHrsNum by RegularMarij
t = -1.2147, df = 116.9, p-value = 0.1135
alternative hypothesis: true difference in means between group No and group Yes is less than 0
95 percent confidence interval:
       -Inf 0.09866006
sample estimates:
 mean in group No mean in group Yes 
          2.02963           2.30000 </code></pre>
</div>
</div>
<div class="notes">
<p>DV: continuous, IV: categories</p>
<p>n.s. (differs from book), although mean is higher in Yes, not significantly different!</p>
</div>
</section>
<section id="comparing-dependent-observations-paired-t-test" class="level2">
<h2 class="anchored" data-anchor-id="comparing-dependent-observations-paired-t-test">Comparing Dependent Observations (Paired <em>t</em>-test)</h2>
<p>If we have repeated observations of the same subject (i.e., a within-subject design), we might want to compare the same subject thus on multiple, <em>repeated measurements</em>.</p>
<p>. . .</p>
<p>If we want to test whether blood pressure differs between the first and second measurement session across individuals, we can use a <strong>paired</strong> <span class="math inline">\(t\)</span><strong>-test</strong>.</p>
<p>In R, we would run a paired-samples <span class="math inline">\(t\)</span>-test like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345678</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>NHANES_sample <span class="ot">&lt;-</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  NHANES <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(Age<span class="sc">&gt;</span><span class="dv">17</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BPSys2) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BPSys1)) <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(BPSys1,BPSys2,ID) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">200</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>NHANES_sample_tidy <span class="ot">&lt;-</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  NHANES_sample <span class="sc">%&gt;%</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gather</span>(timepoint,BPsys,<span class="sc">-</span>ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(NHANES_sample, <span class="fu">t.test</span>(BPSys1, BPSys2, <span class="at">paired =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  BPSys1 and BPSys2
t = 2.7369, df = 199, p-value = 0.006763
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.2850857 1.7549143
sample estimates:
mean difference 
           1.02 </code></pre>
</div>
</div>
<p>Side note: A paired <span class="math inline">\(t\)</span>-test is equivalent to a one-sample <span class="math inline">\(t\)</span>-test, when using the paired differences as <span class="math inline">\(\hat{X}\)</span> and testing them against a value of 0 (if we expect no difference for <span class="math inline">\(H_0\)</span>) for <span class="math inline">\(\mu\)</span>.</p>
<div class="notes">
<p>important: If we run an independent sample t-test, it would probably be n.s.! (check out book)</p>
</div>
</section>
<section id="comparing-more-than-two-means" class="level2">
<h2 class="anchored" data-anchor-id="comparing-more-than-two-means">Comparing More Than Two Means</h2>
<p>Often, we want to compare more than two means, e.g.&nbsp;different treatment groups or timepoints.</p>
<p>Example: Different treatments for blood pressure</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123456</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>nPerGroup <span class="ot">&lt;-</span> <span class="dv">36</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>noiseSD <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>meanSysBP <span class="ot">&lt;-</span> <span class="dv">140</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>effectSize <span class="ot">&lt;-</span> <span class="fl">0.8</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">group=</span><span class="fu">as.factor</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">'placebo'</span>,nPerGroup),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">rep</span>(<span class="st">'drug1'</span>,nPerGroup),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">rep</span>(<span class="st">'drug2'</span>,nPerGroup))),</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">sysBP=</span><span class="cn">NA</span>) </span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>sysBP[df<span class="sc">$</span>group<span class="sc">==</span><span class="st">'placebo'</span>] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(nPerGroup,<span class="at">mean=</span>meanSysBP,<span class="at">sd=</span>noiseSD)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>sysBP[df<span class="sc">$</span>group<span class="sc">==</span><span class="st">'drug1'</span>] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(nPerGroup,<span class="at">mean=</span>meanSysBP<span class="sc">-</span>noiseSD<span class="sc">*</span>effectSize,<span class="at">sd=</span>noiseSD)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>sysBP[df<span class="sc">$</span>group<span class="sc">==</span><span class="st">'drug2'</span>] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(nPerGroup,<span class="at">mean=</span>meanSysBP,<span class="at">sd=</span>noiseSD)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df,<span class="fu">aes</span>(group,sysBP)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W8_ModelingRelationships_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analysis-of-variance-anova" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="analysis-of-variance-anova">Analysis of Variance (ANOVA)</h2>
<p><span class="math inline">\(H_0\)</span>: all means are equal<br>
<span class="math inline">\(H_A\)</span>: not all means are equal (e.g.&nbsp;at least one differs)</p>
<p>. . .</p>
<p>We can <em>partition</em> the variance in the data into different parts:</p>
<p><span class="math inline">\(SS_{total}\)</span> = total variance in the data<br>
<span class="math inline">\(SS_{model}\)</span> = Variance explained by the model*<br>
<span class="math inline">\(SS_{error}\)</span> = Variance <em>not</em> explained by the model</p>
<p>. . .</p>
<p>We can use those to calculate the <em>mean squares</em> for the model and the error:</p>
<p><span class="math inline">\(MS_{model} =\frac{SS_{model}}{df_{model}}= \frac{SS_{model}}{p-1}\)</span> (<span class="math inline">\(p\)</span> is the number of factor levels)</p>
<p><span class="math inline">\(MS_{error} = \frac{SS_{error}}{df_{error}} = \frac{SS_{error}}{N - p}\)</span></p>
<p>. . .</p>
<p>We want to test whether the variance accounted for by the model is greater than expected by chance (<span class="math inline">\(H_0\)</span>: no difference).</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p><span class="math inline">\(SS\)</span> = Sum of Squares, remember that the variance is the sum of the squared deviation of an observation to the mean</p>
<p><span class="math inline">\(MS\)</span> = Mean (Sum of) Squares: How much variance per degree of freedom?</p>
<p>*more on that in the next session!</p>
</div></div><div class="notes">
<p>quite common analysis! We will just scratch the surface</p>
</div>
</section>
<section id="anova-2" class="level2">
<h2 class="anchored" data-anchor-id="anova-2">ANOVA 2</h2>
<p>In R, we would run an ANOVA like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group2=</span><span class="fu">fct_relevel</span>(group,<span class="fu">c</span>(<span class="st">"placebo"</span>,<span class="st">"drug1"</span>,<span class="st">"drug2"</span>)))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reorder the factor levels so that "placebo" is the control condition/intercept!</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># test model without separate duymmies</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>lmResultAnovaBasic <span class="ot">&lt;-</span> <span class="fu">lm</span>(sysBP <span class="sc">~</span> group2, <span class="at">data=</span>df)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmResultAnovaBasic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sysBP ~ group2, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.0838  -7.7452  -0.0978   7.6872  23.4313 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  141.595      1.656  85.502  &lt; 2e-16 ***
group2drug1  -10.237      2.342  -4.371 2.92e-05 ***
group2drug2   -2.027      2.342  -0.865    0.389    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.936 on 105 degrees of freedom
Multiple R-squared:  0.1695,    Adjusted R-squared:  0.1537 
F-statistic: 10.71 on 2 and 105 DF,  p-value: 5.83e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># emm.result &lt;- emmeans(lmResultAnovaBasic, "group" )</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="anova-3" class="level2">
<h2 class="anchored" data-anchor-id="anova-3">ANOVA 3</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmResultAnovaBasic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sysBP ~ group2, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.0838  -7.7452  -0.0978   7.6872  23.4313 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  141.595      1.656  85.502  &lt; 2e-16 ***
group2drug1  -10.237      2.342  -4.371 2.92e-05 ***
group2drug2   -2.027      2.342  -0.865    0.389    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.936 on 105 degrees of freedom
Multiple R-squared:  0.1695,    Adjusted R-squared:  0.1537 
F-statistic: 10.71 on 2 and 105 DF,  p-value: 5.83e-05</code></pre>
</div>
</div>
<p>We can see a <span class="math inline">\(t\)</span>-test for every drug. This is because the <em>factor</em> <code>group2</code> is automatically <strong>dummy coded</strong> by R: We always compare one drug against the intercept, which is the mean of the placebo group!</p>
<p>The <span class="math inline">\(t\)</span>-test shows us that drug1 differs significantly from placebo but not drug2.</p>
<p>The <span class="math inline">\(F\)</span>-statistic (also called <em>omnibus test</em>) actually tests our overall hypothesis of no difference between conditions.</p>
</section>
<section id="anova-side-notes" class="level2">
<h2 class="anchored" data-anchor-id="anova-side-notes">ANOVA side notes</h2>
<p>In R, there are different functions that you can use to run an ANOVA besides <code>lm()</code>, which have different advantages and disadvantages (functions like <code>ezANOVA()</code> from the <code>ez</code> packages or functions from the <code>afex</code> package might be helpful).</p>
<p>Just like with the <span class="math inline">\(t\)</span>-test, there’s also a distinction between <em>between-subjects</em> and <em>within-subjects</em> (i.e., <em>repeated measures ANOVA</em>). The previous example contained just <em>between-subjects</em> measures, i.e.&nbsp;different groups without repeated measures. We will talk about other options later, but see the packages mentioned above as well for functional parameters called, e.g., <code>within</code>.</p>
<div class="notes">
<p>Dummy coded (explicitly):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">d1 =</span> <span class="fu">as.integer</span>(group <span class="sc">==</span> <span class="st">"drug1"</span>), <span class="co"># 1s for drug1, 0s for all other drugs</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">d2 =</span> <span class="fu">as.integer</span>(group <span class="sc">==</span> <span class="st">"drug2"</span>)  <span class="co"># 1s for drug2, 0s for all other drugs</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># fit ANOVA model</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>lmResultANOVA <span class="ot">&lt;-</span> <span class="fu">lm</span>(sysBP <span class="sc">~</span> d1 <span class="sc">+</span> d2, <span class="at">data =</span> df)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmResultANOVA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sysBP ~ d1 + d2, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.0838  -7.7452  -0.0978   7.6872  23.4313 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  141.595      1.656  85.502  &lt; 2e-16 ***
d1           -10.237      2.342  -4.371 2.92e-05 ***
d2            -2.027      2.342  -0.865    0.389    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.936 on 105 degrees of freedom
Multiple R-squared:  0.1695,    Adjusted R-squared:  0.1537 
F-statistic: 10.71 on 2 and 105 DF,  p-value: 5.83e-05</code></pre>
</div>
</div>
<p><span class="math inline">\(t\)</span>-tests: dummy coded = 0 vs.&nbsp;1<br>
- control for multiple comparisons! (later)<br>
- if we wanted to compare the two drugs, we’d have to dummy code/relevel differently or use follow-up comparisons like with emmeans()</p>
<p><span class="math inline">\(F\)</span>: Is our model better than a simple model that just includes the intercept? In this case placebo…</p>
</div>
</section>
</section>
<section id="thanks" class="level1">
<h1>Thanks!</h1>
<p>Learning objectives:</p>
<ul>
<li><p>What are <em>contingency tables</em> and how do we use <span class="math inline">\(\chi^2\)</span>-tests to assess a significant relationship between <em>categorical</em> variables?</p></li>
<li><p>Be able to describe what a <em>correlation coefficient</em> is and compute &amp; interpret it.</p></li>
<li><p>Know what a <span class="math inline">\(t\)</span>-test &amp; ANOVA is and how to compute and interpret it.</p></li>
</ul>
<p>Next:</p>
<p>Practical exercises in R!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>