<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Mario Reutter (slides adapted from Dr.&nbsp;Lea Hildebrandt)">

<title>Biostatistics - 09 Statistical Analyses in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./W9_FirstAnalysisR.html">09 Statistical Analyses in R</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W1_Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01a Introduction to Biostatistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W1b_IntroR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01b Intro to R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W2_Models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W3_DataWranglingR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 Data Wrangling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W4_DataVizR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 Data Visualization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W5_Sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05 Probabilities &amp; Sampling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W6_ProbabilityR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">06 Probability &amp; Sampling in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W7_Hypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07 Hypothesis Testing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W8_ModelingRelationships.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">08 Modeling Relationships</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W9_FirstAnalysisR.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">09 Statistical Analyses in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W10_GLM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10 The General Linear Model &amp; Multivariate Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W11_GLMinR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11 ANOVA &amp; the General Linear Model in R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W12_LMM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12 Linear Mixed Models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W13_RMarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">13 R Markdown</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./W15_RepResearchR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">15 Reproducible Research</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="W9_FirstAnalysisR.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">09 Statistical Analyses in R</h1>
<p class="subtitle lead"></p><div class="line-block">Julius-Maximilians-University Würzburg<br>
Course: “Biostatistics”<br>
Translational Neuroscience</div><p></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Mario Reutter (slides adapted from Dr.&nbsp;Lea Hildebrandt) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="kinds-of-statistical-analyses" class="level1">
<h1>Kinds of Statistical Analyses</h1>
<p>Last session, we have heard about Chi² tests, <em>t</em>-tests, correlations, and ANOVA. Today we will apply them in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode css code-with-copy"><code class="sourceCode css"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>code<span class="fu">.sourceCode</span> {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="kw">font-size</span><span class="ch">:</span> <span class="dv">1.4</span><span class="dt">em</span><span class="op">;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>div<span class="fu">.cell-output-stdout</span> {</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="kw">font-size</span><span class="ch">:</span> <span class="dv">1.4</span><span class="dt">em</span><span class="op">;</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<style type="text/css">
code.sourceCode {
  font-size: 1.4em;
}

div.cell-output-stdout {
  font-size: 1.4em;
}
</style>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:dplyr':

    recode</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="notes">
<p>which analysis do you use when you have two categorical etc. variables?</p>
</div>
<section id="set-up" class="level2">
<h2 class="anchored" data-anchor-id="set-up">Set Up</h2>
<ol type="1">
<li><p>Open RStudio and load your Biostats R project. Create a new script called <code>DataAnalysis1.R</code>.</p></li>
<li><p>Install and load new packages you’ll need: <code>car</code>, <code>effectsize</code>, and <code>apa</code>.</p></li>
</ol>
</section>
</section>
<section id="activity-1" class="level1">
<h1>Activity 1</h1>
<p>Which test would you choose if you wanted to test whether a variable is differently distributed between groups?</p>
<p>Let’s say we have tested 20 mice and want to know whether they pressed the blue, green, or red lever more often than by chance. This is how often the mice pressed each lever: Blue = 5, Green = 4, Red = 11</p>
<p>. . .</p>
<p>We would run a (one-sample) <strong>Chi²-test</strong>!</p>
<p>Remember that in a Chi²-test, we would compare observed to expected counts:</p>
<p><span class="math display">\[
\chi^2 = \sum\frac{(Observed - Expected)^2}{Expected}
\]</span></p>
<section id="one-sample-chi²-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-chi²-test">One Sample Chi²-Test</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Input data into R</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>lever_presses <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">levers=</span><span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"blue"</span>, <span class="dv">5</span>), <span class="fu">rep</span>(<span class="st">"green"</span>, <span class="dv">4</span>), <span class="fu">rep</span>(<span class="st">"red"</span>, <span class="dv">11</span>))) <span class="sc">%&gt;%</span> <span class="co">#data in usual format</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(levers) <span class="co">#convert to a frequency table</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># run Chi² test</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>chi2_lever <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(lever_presses <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">names_from=</span><span class="st">"levers"</span>, <span class="at">values_from=</span><span class="st">"n"</span>)) <span class="co">#wide format needed</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co">#chi2_lever &lt;- chisq.test(tibble(blue=5, green=4, red=11)) #enter data directly as summary table</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>chi2_lever <span class="sc">%&gt;%</span> apa<span class="sc">::</span><span class="fu">chisq_apa</span>() <span class="co">#output results</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>chi^2(2) = 4.30, p = .116</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add expected count and residuals to data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>lever_presses <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">expected =</span> chi2_lever<span class="sc">$</span>expected, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">residuals =</span> chi2_lever<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  levers     n expected residuals
  &lt;chr&gt;  &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 blue       5     6.67    -0.645
2 green      4     6.67    -1.03 
3 red       11     6.67     1.68 </code></pre>
</div>
</div>
<div class="notes">
<p>Is sample size not important for significance here? <span class="math display">\[\chi^2 = \sum\frac{(Observed - Expected)^2}{Expected}\]</span> More observations =&gt; easier to see greater absolute difference between observed and expected values =&gt; gets squared and therefore “outcompetes” denominator (what about expected reductions in sampling error?)</p>
</div>
</section>
<section id="chi²-test-2" class="level2">
<h2 class="anchored" data-anchor-id="chi²-test-2">Chi²-Test 2</h2>
<p>We can also run a Chi²-test for two variables, such as if we want to know whether the lever presses differ per group.</p>
<p>Let’s say we have a treatment and a control group and we record the different lever presses:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: center;">Blue</th>
<th style="text-align: center;">Green</th>
<th style="text-align: center;">Red</th>
<th style="text-align: center;"><strong>Totals</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treatment</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;"><strong>20</strong></td>
</tr>
<tr class="even">
<td>Control</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;"><strong>20</strong></td>
</tr>
<tr class="odd">
<td><strong>Totals</strong></td>
<td style="text-align: center;"><strong>8</strong></td>
<td style="text-align: center;"><strong>16</strong></td>
<td style="text-align: center;"><strong>16</strong></td>
<td style="text-align: center;"><strong>40</strong></td>
</tr>
</tbody>
</table>
<p>Remember: We use the assumption of independence to calculate the expected values.</p>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lever_presses2 <span class="ot">=</span> <span class="fu">tibble</span>(<span class="at">group=</span><span class="st">"treatment"</span>, <span class="at">blue=</span><span class="dv">3</span>, <span class="at">green=</span><span class="dv">12</span>, <span class="at">red=</span><span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(<span class="fu">tibble</span>(<span class="at">group=</span><span class="st">"control"</span>, <span class="at">blue=</span><span class="dv">5</span>, <span class="at">green=</span><span class="dv">4</span>, <span class="at">red=</span><span class="dv">11</span>)) <span class="co">#clearest way to manually input data</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#for long data, you create the frequency table identically to previous slide but with: count(group, levers)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(lever_presses2 <span class="sc">%&gt;%</span> <span class="fu">column_to_rownames</span>(<span class="st">"group"</span>)) <span class="sc">%&gt;%</span> apa<span class="sc">::</span><span class="fu">chisq_apa</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(lever_presses2 %&gt;% column_to_rownames("group")):
Chi-Quadrat-Approximation kann inkorrekt sein</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>chi^2(2) = 6.75, p = .034</code></pre>
</div>
</div>
</section>
<section id="assumptions-of-chi²-tests" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-chi²-tests">Assumptions of Chi²-Tests</h2>
<div class="incremental">
<ul class="incremental">
<li><p><strong>Random sample</strong></p></li>
<li><p><strong>Categorical variables</strong>, i.e., <strong>counts</strong> within (combinations of) groups</p></li>
<li><p><strong>Expected cell count</strong>: &gt;5 counts per cell</p></li>
<li><p><strong>Independence</strong>: Each observation is independent of the others, e.g.&nbsp;there are no repeated measurements/paired data (within-subjects data are correlated!)</p></li>
</ul>
</div>
<p>. . .</p>
<p>In the case of the last analysis, we got a <em>warning</em> because the expected cell sizes were too small. In this case, it is better to use <strong>Fisher’s exact test</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(lever_presses2 <span class="sc">%&gt;%</span> <span class="fu">column_to_rownames</span>(<span class="st">"group"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  lever_presses2 %&gt;% column_to_rownames("group")
p-value = 0.04168
alternative hypothesis: two.sided</code></pre>
</div>
</div>
</section>
</section>
<section id="activity-2" class="level1">
<h1>Activity 2</h1>
<p>Now imagine you want to compare <em>reaction times</em> of the lever presses of the two groups of mice. You expect that those in the treatment group respond faster than those in the control group. Which statistical test would you use?</p>
<p>. . .</p>
<p><em>Hint</em>: We now have two <em>independent</em> groups and a <em>continuous</em> dependent variable (reaction times).</p>
<p>. . .</p>
<p>An (independent samples) <em>t</em>-test!</p>
<p>. . .</p>
<section id="t-test-setup" class="level2">
<h2 class="anchored" data-anchor-id="t-test-setup"><em>t</em>-test setup</h2>
<p>To run a <em>t</em>-Test, let’s first simulate data. What happens here?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">31415</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sim_data_t <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"treatment"</span>, <span class="st">"control"</span>), <span class="at">each=</span><span class="dv">20</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">reaction_times =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">400</span>, <span class="dv">100</span>), <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">450</span>, <span class="dv">100</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualize</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_data_t, <span class="fu">aes</span>(<span class="at">x=</span>group, <span class="at">y=</span>reaction_times)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="t-test" class="level2">
<h2 class="anchored" data-anchor-id="t-test"><em>t</em>-Test</h2>
<p>We can use the <em>formula</em> notation to run the <em>t</em>-test. This notation usually looks like this:<br>
<code>dependent variable ~ independent variable.</code></p>
<p>Replace the <code>NULL</code>s:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="cn">NULL</span> <span class="sc">~</span> <span class="cn">NULL</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> <span class="cn">NULL</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="cn">NULL</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">NULL</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(reaction_times <span class="sc">~</span> group,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> sim_data_t,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="co">#depends on ALPHABETICAL order of groups in data!</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>       <span class="co">#paired = FALSE # this is the default, so no need to specify it</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  reaction_times by group
t = 1.9841, df = 34.42, p-value = 0.02763
alternative hypothesis: true difference in means between group control and group treatment is greater than 0
95 percent confidence interval:
 10.02639      Inf
sample estimates:
  mean in group control mean in group treatment 
               468.0592                400.3289 </code></pre>
</div>
</div>
<p>. . .</p>
<p>As you can see in the output, R automatically chose to run Welch’s <em>t</em>-test, which does not assume <strong>variance homogeneity</strong> in contrast to Student’s <em>t</em>-test. For the latter, you can add the function parameter <code>var.equal = TRUE</code></p>
<div class="notes">
<p>When changing the name “treatment” to “a”, the results change:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(reaction_times <span class="sc">~</span> group,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">group =</span> <span class="fu">ifelse</span>(group<span class="sc">==</span><span class="st">"treatment"</span>, <span class="st">"a"</span>, group)),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"greater"</span>, <span class="co">#depends on order of groups in data! 1st group &gt; 2nd group</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> apa<span class="sc">::</span><span class="fu">t_apa</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t(38) = -1.98, p = .973, d = -0.63</code></pre>
</div>
</div>
</div>
</section>
<section id="t-test-alternatives" class="level2">
<h2 class="anchored" data-anchor-id="t-test-alternatives"><em>t</em>-Test: alternatives</h2>
<p>You can also supply two vectors of numerical values for the groups:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group<span class="sc">==</span><span class="st">"treatment"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(reaction_times),</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group<span class="sc">==</span><span class="st">"control"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(reaction_times),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"less"</span>) <span class="co">#more intuitive now because you can filter for treatment first</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sim_data_t %&gt;% filter(group == "treatment") %&gt;% pull(reaction_times) and sim_data_t %&gt;% filter(group == "control") %&gt;% pull(reaction_times)
t = -1.9841, df = 34.42, p-value = 0.02763
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
      -Inf -10.02639
sample estimates:
mean of x mean of y 
 400.3289  468.0592 </code></pre>
</div>
</div>
<p>. . .</p>
<p>More useful output with <code>apa</code> package (only for Student’s t-tests):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group<span class="sc">==</span><span class="st">"treatment"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(reaction_times),</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">filter</span>(group<span class="sc">==</span><span class="st">"control"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(reaction_times),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"less"</span>, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  apa<span class="sc">::</span><span class="fu">t_apa</span>(<span class="at">es_ci=</span>T) <span class="co">#optional: confidence interval around effect size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t(38) = -1.98, p = .027, d = -0.63 [-1.26; 0.01]</code></pre>
</div>
</div>
<p>. . .</p>
<p>For paired t-tests, you can also work with the wide format of data (advantage: missing values become explicit):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>sim_data_t_wide <span class="ot">=</span> sim_data_t <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">subject=</span><span class="fu">rep.int</span>(<span class="dv">1</span><span class="sc">:</span>(<span class="fu">n</span>()<span class="sc">/</span><span class="dv">2</span>), <span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from=</span><span class="st">"group"</span>, <span class="at">values_from=</span><span class="st">"reaction_times"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> sim_data_t_wide <span class="sc">%&gt;%</span> <span class="fu">pull</span>(treatment),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> sim_data_t_wide <span class="sc">%&gt;%</span> <span class="fu">pull</span>(control),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">"less"</span>, </span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  apa<span class="sc">::</span><span class="fu">t_apa</span>(<span class="at">es_ci=</span>T) <span class="co">#optional: confidence interval around effect size</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t(19) = -1.98, p = .031, d = -0.44 [-0.90; 0.02]</code></pre>
</div>
</div>
</section>
<section id="assumptions-of-t-tests" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-t-tests">Assumptions of <em>t</em>-Tests</h2>
<p>Before we run a <em>t</em>-test, we also want to check the assumptions for violations:</p>
<div class="incremental">
<ul class="incremental">
<li><p>The dependent variable is continuous (otherwise: chi²-test)</p></li>
<li><p>The data are independent (otherwise: <em>paired</em> sample <em>t</em>-test)</p></li>
<li><p>The variance between the groups is homogeneous (only for Student’s <em>t</em>-test, R uses Welch’s test by default)</p></li>
<li><p>The <em>residuals</em>&nbsp;are normally distributed for each group (otherwise: <code>wilcox.test</code>)</p></li>
</ul>
</div>
<p>. . .</p>
<p>Oftentimes, the last assumption is misquoted as: “The <em>dependent variable</em> needs to be normally distributed”.<br>
In fact, only its <em>sampling distribution</em> needs to be (blue vs.&nbsp;grey distribution in the lecture on sampling [<a href="https://spressi.github.io/biostats/W5_Sampling.html#/example-sampling-distribution">direct link</a>]), which will always be the case for big enough samples due to the central limit theorem.</p>
</section>
<section id="assumptions-of-t-tests-2" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-t-tests-2">Assumptions of <em>t</em>-Tests 2</h2>
<p><strong>Test for normality of <em>residuals</em></strong> (for both groups): If points fall along the line nicely, assumption is met.</p>
<div class="cell" data-output-location="column">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> sim_data_t <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"treatment"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group_resid =</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>           reaction_times <span class="sc">-</span> <span class="fu">mean</span>(reaction_times)) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(group_resid)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co">#base R QQ plot</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(treatment)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-output-location="column">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>control <span class="ot">&lt;-</span> sim_data_t <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="st">"control"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group_resid =</span> reaction_times <span class="sc">-</span> <span class="fu">mean</span>(reaction_times)) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(group_resid)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co">#car's version highlighting (and returning) problematic values</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">qqPlot</span>(control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18  4</code></pre>
</div>
</div>
</section>
<section id="assumptions-of-t-tests-3" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-t-tests-3">Assumptions of <em>t</em>-Tests 3</h2>
<p>Alternatively, we can also run a <strong>Shapiro-Wilk</strong> test to test for <strong>deviations</strong> from normality:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  treatment
W = 0.91403, p-value = 0.0761</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  control
W = 0.96812, p-value = 0.7147</code></pre>
</div>
</div>
<p>If the test is non-significant, then we can conclude that normality of residuals is <strong>not</strong> violated.</p>
<div class="notes">
<ol type="1">
<li>Transform your data to try and normalise the distribution. Not usually recommended these days but some still use it.</li>
<li>Use a non-parametric test. The non-parametric equivalent of the independent t-test is the Mann-Whitney and the equivalent of the paired-samples t-test is the Wilcoxon signed-ranks test. Though more modern permutation tests are better.</li>
<li>Do nothing. <a href="https://www.rips-irsp.com/articles/10.5334/irsp.82/">Delacre, Lakens &amp; Leys, 2017</a> argue that with a large enough sample (&gt;30), the Welch test is robust to deviations from assumptions. With very large samples normality is even less of an issue, so design studies with large samples.</li>
</ol>
</div>
</section>
</section>
<section id="optional-activity-paired-samples-t-test" class="level1">
<h1>Optional Activity: Paired Samples <em>t</em>-Test</h1>
<p>Sometimes you have dependent data: These data are somehow correlated, e.g.&nbsp;they belong to the same subject (that you measured repeatedly across a <em>within-subject manipulation</em>).</p>
<p>. . .</p>
<p>In this case, you would use a <strong>paired-samples <em>t</em>-test</strong>.</p>
<p>. . .</p>
<p>Let’s run such a <em>t</em>-test with real data. We’ll use the <a href="https://github.com/spressi/biostats/blob/main/Data/Mehr%20Song%20and%20Spelke%202016%20Experiment%201.csv"><code>Mehr Song and Spelke 2016 Experiment 1.csv</code></a> file (note that this is not a good file name!).</p>
<p>In this dataset, the authors examined whether infants exposed to certain songs would recognize strangers singing these lullabies as part of their social group. Parents sang certain lullabies to their infants for 1-2 weeks. During the experiment, the infants looked at videos of two strangers: First the strangers were just smiling (baseline phase), then they would sing either the familiar or an unfamiliar lullaby. Finally, the infants again saw the videos of the strangers smiling (test phase). Eye-tracking (duration looked at each stranger) was measured.</p>
<p>. . .</p>
<p>Load the file into your Environment. Run the code and explain what happens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>gaze <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Mehr Song and Spelke 2016 Experiment 1.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(exp1 <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">baseline =</span> Baseline_Proportion_Gaze_to_Singer,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">test =</span> Test_Proportion_Gaze_to_Singer) <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, baseline, test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 96 Columns: 153
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (7): study_code, dob, dot1, dot2, dot3, stim, module
dbl (146): id, exp1, exp2, exp3, exp4, exp5, female, dad, train, Baseline_Pr...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<section id="assumptions-of-the-paired-samples-t-test" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-of-the-paired-samples-t-test">Assumptions of the Paired-Samples <em>t</em>-Test</h2>
<ol type="1">
<li><p>The data are continuous.</p></li>
<li><p>All participants should appear in both conditions/groups.</p></li>
<li><p>The <em>residuals</em> are normally distributed.</p></li>
</ol>
<p>. . .</p>
<p>A paired-samples <em>t</em>-test actually tests whether the <em>difference</em> between two measurements is significantly different from 0 (= no difference/effect).</p>
<p>In our example data, this means that the <code>test</code> values are subtracted from the <code>baseline</code> values, and this difference is used as data.</p>
<p>To test the assumption that residuals are normally distributed, we thus calculate the residuals as follow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>gaze_residual <span class="ot">&lt;-</span> gaze <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> baseline <span class="sc">-</span> test) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">group_resid =</span> diff <span class="sc">-</span> <span class="fu">mean</span>(diff))</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(gaze_residual<span class="sc">$</span>group_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22 29</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(gaze_residual<span class="sc">$</span>group_resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  gaze_residual$group_resid
W = 0.97818, p-value = 0.7451</code></pre>
</div>
</div>
</section>
<section id="descriptives-visualization" class="level2">
<h2 class="anchored" data-anchor-id="descriptives-visualization">Descriptives &amp; Visualization</h2>
<p>For the visualization, we need the data in long format (this is identical for between-subject groups):</p>
<div class="cell" data-output-location="column">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gaze_tidy <span class="ot">&lt;-</span> gaze <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">names_to =</span> <span class="st">"phase"</span>, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"looking_time"</span>, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">cols =</span> <span class="fu">c</span>(baseline, test))</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># boxplot</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>gaze_tidy <span class="sc">%&gt;%</span> </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>phase, <span class="at">y=</span>looking_time)) <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br>
We can also calculate the means and SDs per phase:</p>
<div class="cell" data-output-location="column">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>gaze_tidy <span class="sc">%&gt;%</span> </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_looking =</span> <span class="fu">mean</span>(looking_time),</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_looking =</span> <span class="fu">sd</span>(looking_time),</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> phase)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  phase    mean_looking sd_looking     n
  &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
1 baseline        0.521      0.177    32
2 test            0.593      0.179    32</code></pre>
</div>
</div>
</section>
<section id="paired-samples-t-test-in-r" class="level2">
<h2 class="anchored" data-anchor-id="paired-samples-t-test-in-r">Paired Samples <em>t</em>-Test in R</h2>
<p>Any ideas how you would specify the paired samples <em>t</em>-test in R?</p>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaze, <span class="fu">t.test</span>(<span class="cn">NULL</span>, <span class="cn">NULL</span>,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">paired =</span> <span class="cn">NULL</span>,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alternative =</span> <span class="cn">NULL</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaze, <span class="fu">t.test</span>(baseline, test,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">paired =</span> <span class="cn">TRUE</span>,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alternative =</span> <span class="st">"two.sided"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  baseline and test
t = -2.4164, df = 31, p-value = 0.02175
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.13349698 -0.01129217
sample estimates:
mean difference 
    -0.07239458 </code></pre>
</div>
</div>
</section>
<section id="effect-size-for-the-t-test" class="level2">
<h2 class="anchored" data-anchor-id="effect-size-for-the-t-test">Effect Size for the <em>t</em>-Test</h2>
<p>You can (and should!) of course calculate and report effect sizes for your test statistics to get an impression of how practically relevant the effect is.</p>
<p>For the <em>t</em>-tests, you would calculate <strong>Cohen’s d</strong> (using the function from the <code>effectsize</code> package):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaze, effectsize<span class="sc">::</span><span class="fu">cohens_d</span>(baseline, test, <span class="at">paired=</span>T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>For paired samples, 'repeated_measures_d()' provides more options.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohen's d |         95% CI
--------------------------
-0.43     | [-0.79, -0.06]</code></pre>
</div>
</div>
<p>. . .</p>
<p><br>
Or just use the <code>apa</code> package and you get everything in one go:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaze, <span class="co">#the with function allows to call columns as if they were variables (but pipe function doesn't work with it)</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">t.test</span>(baseline, test, <span class="at">paired =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  apa<span class="sc">::</span><span class="fu">t_apa</span>(<span class="at">es_ci=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>t(31) = -2.42, p = .022, d = -0.43 [-0.79; -0.06]</code></pre>
</div>
</div>
<!--
## Write Up of the *t*-Test

What do you think you should report in your results section?

. . .

-   the means and SDs per condition (or the mean difference and the SD of the difference between conditions)

-   the test statistic *t,* incl. degrees of freedom

-   the p-value

-   the effect size

. . .

> At test stage (M = .59, SD = .18), infants showed a significantly longer preferential looking time to the singer of the familiar melody than they had shown the same singer at baseline (M = .52, SD = .18), *t*(31) = 2.42, *p* = .022, *d* = .41.
-->
</section>
<section id="summary-optional-activity" class="level2">
<h2 class="anchored" data-anchor-id="summary-optional-activity">Summary: Optional Activity</h2>
<div class="incremental">
<ul class="incremental">
<li><p>Most things are similar between independent and dependent sample <em>t</em>-tests</p></li>
<li><p>Make sure to include <code>paired=T</code> for repeated measures to get correct results</p></li>
<li><p>Recommendation: Use <code>apa::t_apa()</code> with <code>es.ci=T</code> to get (most of) the information you need</p></li>
<li><p>It is often a good idea to also report means and standard deviations per group (<code>summarise</code> with <code>.by</code> argument)</p></li>
<li><p>Plotting: Unfortunately, (between subjects) confidence intervals are not diagnostic for the significance of dependent samples. Instead, we need the <strong>confidence interval around the paired differences (i.e., the within subject changes)</strong>. Since this is not easy to do and there is little consensus yet, I will just raise awareness here.</p></li>
</ul>
</div>
</section>
</section>
<section id="correlation-preparation" class="level1">
<h1>Correlation: Preparation</h1>
<p>If we have two continuous variables, we can look at their relationship using <strong>correlation</strong>. In the data you just used, we have two continuous variables: the repeated measures of gaze.</p>
<p>If you skipped the previous activity, here is what you need:</p>
<ol type="1">
<li><p>Download <a href="https://github.com/spressi/biostats/blob/main/Data/Mehr%20Song%20and%20Spelke%202016%20Experiment%201.csv"><code>Mehr Song and Spelke 2016 Experiment 1.csv</code></a> (download button near the top right) into your project folder and</p></li>
<li><p>run this code:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>gaze <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Mehr Song and Spelke 2016 Experiment 1.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(exp1 <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">baseline =</span> Baseline_Proportion_Gaze_to_Singer,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">test =</span> Test_Proportion_Gaze_to_Singer) <span class="sc">%&gt;%</span> </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, baseline, test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="correlation-test" class="level2">
<h2 class="anchored" data-anchor-id="correlation-test">Correlation Test</h2>
<p>With these data, we might be interested in whether there is a relationship between the two measures of gaze, i.e., whether those children who looked at the stranger more at baseline would also be the ones who looked at the stranger more often at the follow-up test (here: indicating stability of preferences).</p>
<p>. . .</p>
<p>Similar to the paired <em>t</em>-Test, the continuous variables are also “paired” within subjects. Thus, we can a similar syntax that is easier for a wide format of data (<code>gaze</code> instead of <code>gaze_tidy</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> gaze <span class="sc">%&gt;%</span> <span class="fu">pull</span>(baseline), </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> gaze <span class="sc">%&gt;%</span> <span class="fu">pull</span>(test), </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  gaze %&gt;% pull(baseline) and gaze %&gt;% pull(test)
t = 3.5686, df = 30, p-value = 0.00123
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2435655 0.7515352
sample estimates:
      cor 
0.5458966 </code></pre>
</div>
</div>
<p>Note: We don’t have to indicate <code>paired=T</code> because correlations only work for paired values.</p>
</section>
<section id="correlations-write-up" class="level2">
<h2 class="anchored" data-anchor-id="correlations-write-up">Correlations: Write Up</h2>
<p>Once again, the <code>apa</code> package offers help to summarize the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> gaze <span class="sc">%&gt;%</span> <span class="fu">pull</span>(baseline), </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> gaze <span class="sc">%&gt;%</span> <span class="fu">pull</span>(test), </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">alternative =</span> <span class="st">"two.sided"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  apa<span class="sc">::</span><span class="fu">cor_apa</span>(<span class="at">r_ci=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>r(30) = .55 [.24; .75], p = .001</code></pre>
</div>
</div>
<p>. . .</p>
<p>You can even use <code>report()</code> to get an automatic suggestion of how to report the results (works with a lot of different models!).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(report)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(gaze, <span class="fu">cor.test</span>(<span class="at">x =</span> baseline, </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">y =</span> test, </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">alternative =</span> <span class="st">"two.sided"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">report</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effect sizes were labelled following Funder's (2019) recommendations.

The Pearson's product-moment correlation between baseline and test is positive,
statistically significant, and very large (r = 0.55, 95% CI [0.24, 0.75], t(30)
= 3.57, p = 0.001)</code></pre>
</div>
</div>
<div class="notes">
<p>We mainly use this dataset so that you don’t have to load another one, but in practice you would either run a <em>t</em>-test or a correlation, not necessarily both!</p>
<p>The t-tests answers whether there is a change across all participants between the two time points, the correlation answers the question whether those who score high at one time point would also score high at the next (regardless of overall level).</p>
</div>
</section>
<section id="correlations-notes" class="level2">
<h2 class="anchored" data-anchor-id="correlations-notes">Correlations: Notes</h2>
<p>There are also some <strong>assumptions</strong> that need to be checked:</p>
<ol type="1">
<li><p>Are the data <em>continuous</em>? (for ordinal values: Spearman’s rho)</p></li>
<li><p>Is there a data point for each participant on both variables? (paired values)</p></li>
<li><p>Are the residuals <em>normally distributed</em>?</p></li>
<li><p>Does the relationship between variables appear <em>linear</em>?</p></li>
<li><p>Does the spread have <em>homoscedasticity</em>? (Variance of residuals should be constant across x-axis)<br>
Note: This is very hard to judge by eye and is not the same as the confidence band around the regression line to show constant width. In fact, the latter will always be larger near the ends of the regression line due to how it is computed.</p></li>
</ol>
<p>Please see <a href="https://psyteachr.github.io/quant-fun-v2/correlations.html#assumptions-of-the-test">the text book for how to test these assumptions</a>.</p>
<p>. . .</p>
<p>You should - as always - report the descriptive statistics (summary statistics such as mean and SD).</p>
<p>. . .</p>
<p>You can also report and visualize multiple correlations at once, using a scatterplot matrix or heatmaps. Check out e.g.&nbsp;the <code>corrplot</code> package!</p>
</section>
</section>
<section id="activity-3" class="level1">
<h1>Activity 3</h1>
<p>What if we have more than two groups and/or more than one variable? For example, what if we have one variable <code>treatment</code> (with the factor levels <em>treatment 1, treatment 2,</em> and <em>control</em>) and possibly another variable called <code>timepoint</code> (<em>baseline, post-test</em>)?</p>
<p>Which statistical test could we use?</p>
<p>. . .</p>
<p>We would possibly run an ANOVA!</p>
<p>If we have only one factor (e.g.&nbsp;treatment with three factor levels), we would do an <strong>one-way ANOVA</strong>.<br>
If we have more than one factor but only between-subjects variables, we would run an <strong>ANOVA</strong>.<br>
If we have at least one within-subjects factor, we would run a <strong>repeated measures (or mixed) ANOVA</strong>.</p>
<p>The names are only there for historical reasons. With the right R packages, we only have to ask ourselves if a variable changes between subjects or within subjects.</p>
<p>Due to their potency and wide-spread use, we will cover ANOVAs even more next week in the context of the <strong>linear model</strong>.</p>
<div class="notes">
<p>we will today only look at one-way anovas! Next week we will cover the case when we have more than one IV/predictor!</p>
</div>
<section id="one-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova">One-Way ANOVA</h2>
<p>For this activity, we will use data from a study about memory of traumatic events (see <a href="https://psyteachr.github.io/quant-fun-v2/one-way-anova.html">the textbook</a> for details). In short, the authors of the paper were interested to find out whether:</p>
<blockquote class="blockquote">
<p>reconsolidation - the process during which memories become malleable when recalled - can be blocked using a cognitive task and whether such an approach can reduce these unbidden intrusions.</p>
</blockquote>
<div class="incremental">
<ol class="incremental" type="1">
<li><p>Download the data <a href="https://github.com/spressi/biostats/blob/main/Data/James%20Holmes_Expt%202_DATA.csv"><code>James Holmes_Expt 2_DATA.csv</code></a>. This time, put it in a <strong>subfolder</strong> of your project called “Data”.</p></li>
<li><p>Add a column to the dataframe called <code>subject</code> that equals the <code>row_number()</code>, which will act as a participant ID.</p></li>
<li><p><code>rename()</code>: <code>Days_One_to_Seven_Image_Based_Intrusions_in_Intrusion_Diary</code> to <code>intrusions.</code></p></li>
<li><p>Select only the columns <code>subject</code>, <code>Condition</code> and <code>intrusions</code>.</p></li>
<li><p>Change the variable <code>Condition</code> from <code>numeric</code> to a <code>factor</code> using <code>as.factor()</code></p></li>
</ol>
</div>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/James Holmes_Expt 2_DATA.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">"subject"</span>) <span class="sc">%&gt;%</span> <span class="co">#mutate(subject = 1:n()) %&gt;% </span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">intrusions =</span> Days_One_to_Seven_Image_Based_Intrusions_in_Intrusion_Diary) <span class="sc">%&gt;%</span> </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(subject, Condition, intrusions) <span class="sc">%&gt;%</span> </span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Condition =</span> <span class="fu">as.factor</span>(Condition))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 72 Columns: 28
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (28): Condition, Time_of_Day, BDI_II, STAI_T, pre_film_VAS_Sad, pre_film...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="notes">
<p>we will today only look at one-way anovas! Next week we will cover the case when we have more than one IV/predictor!</p>
</div>
</section>
<section id="one-way-anova-2" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-2">One-Way ANOVA 2</h2>
<p>Create summary/descriptive statistics and visualize the data.</p>
<p>As summary statistics, we want the mean, SD, and SE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">=</span> <span class="cf">function</span>(x, <span class="at">na.rm =</span> <span class="cn">FALSE</span>) { <span class="fu">sd</span>(x, na.rm) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="cf">if</span>(<span class="sc">!</span>na.rm) <span class="fu">length</span>(x) <span class="cf">else</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(x))) }</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>sum_dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(intrusions),</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(intrusions),</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">se =</span> <span class="fu">se</span>(intrusions),</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> Condition)</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sum_dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  Condition  mean    sd    se
  &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 1          5.11  4.23 0.996
2 2          1.89  1.75 0.411
3 3          3.89  2.89 0.681
4 4          4.83  3.33 0.785</code></pre>
</div>
</div>
<p>Note: The names of the factor levels are missing. If we wanted to plot the data, we should have added them in the previous step. For brevity, we will not do it this time.</p>
<!--
. . .



::: {.cell output-location='column-fragment'}

```{.r .cell-code}
ggplot(sum_dat, aes(x = Condition, y = mean, fill = Condition)) +
  stat_summary(fun = "mean", geom = "bar", show.legend = FALSE) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.25) +
  scale_x_discrete(labels = c("No-task control", "Reactivation plus Tetris", "Tetris only", "Reactivation only")) +
  scale_y_continuous(limits = c(0,7), 
                     breaks = c(0,1,2,3,4,5,6,7), 
                     name = "Intrusive-Memory Frequency (Mean for the Week)") 
```

::: {.cell-output-display}
![](W9_FirstAnalysisR_files/figure-html/unnamed-chunk-32-1.png){width=672}
:::
:::


-->
<div class="notes">
<p>don’t use a bar chart!</p>
</div>
</section>
<section id="one-way-anova-3" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-3">One-Way ANOVA 3</h2>
<ol type="1">
<li>Run the ANOVA using <code>lm()</code> and formula notation.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(intrusions <span class="sc">~</span> Condition, <span class="at">data =</span> dat)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: intrusions
          Df Sum Sq Mean Sq F value  Pr(&gt;F)  
Condition  3 114.82  38.273  3.7948 0.01409 *
Residuals 68 685.83  10.086                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Using <code>afex::aov_ez</code>:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Lade nötiges Paket: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Die folgenden Objekte sind maskiert von 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>************
Welcome to afex. For support visit: http://afex.singmann.science/</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attache Paket: 'afex'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Das folgende Objekt ist maskiert 'package:lme4':

    lmer</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(<span class="at">id =</span> <span class="st">"subject"</span>, <span class="co"># the column containing the subject IDs</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">dv =</span> <span class="st">"intrusions"</span>, <span class="co"># the DV </span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">between =</span> <span class="st">"Condition"</span>, <span class="co"># the between-subject variable</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">es =</span> <span class="st">"pes"</span>, <span class="co"># can output an effect size! we want partial eta-squared</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">type =</span> <span class="dv">3</span>, <span class="co"># there are both reasons for 2 and 3 (not covered here)</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">include_aov =</span> <span class="cn">TRUE</span>, <span class="co"># needed for some calculations with emmeans but takes longer</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Contrasts set to contr.sum for the following variables: Condition</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: intrusions
          num Df den Df    MSE      F     ges  Pr(&gt;F)  
Condition      3     68 10.086 3.7948 0.14341 0.01409 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="checking-the-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-assumptions">Checking the Assumptions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(mod1) <span class="co"># doesn't work for ezANOVA output!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># "manually" check normality of residuals </span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(mod<span class="sc">$</span>aov<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="W9_FirstAnalysisR_files/figure-html/unnamed-chunk-35-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3 57</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(mod<span class="sc">$</span>aov<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  mod$aov$residuals
W = 0.87739, p-value = 4.252e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check homogeneity of variance</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">test_levene</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Variances differ between groups (Levene's Test, p = 0.039).</code></pre>
</div>
</div>
<p>Both assumptions are not met!</p>
<p><strong>But</strong> ANOVAS are quite robust to (minor) deviations…</p>
<p>(if the assumptions are violated more, you could…<br>
- run a non-parametric test (Kruskall-Wallis for between-subjects designs of Friedman for repeated measures)<br>
- transform the data (see Field et al., 2009)<br>
- use bootstrapping (see Field et al., 2009)</p>
</section>
<section id="post-hoc-tests" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-tests">Post-Hoc Tests</h2>
<p>So now we know that there are differences between the <code>Condition</code>s, but we don’t know yet which groups differ from each other. We could thus calculate <em>pairwise comparisons</em> or <em>post-hoc t-tests</em> to compare each condition to the others by by filtering the data (so that only two conditions remain) and running <em>t</em>-tests.</p>
<p>A more convenient way is to use the <code>emmeans()</code> function from the package with the same name. We can also adjust the tests for <em>multiple comparisons</em> directly.</p>
<p>We could also define specific <em>contrasts</em> to test <strong>a priori</strong> (i.e., based on hypotheses). But we will skip this here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>mod <span class="sc">%&gt;%</span> <span class="fu">emmeans</span>(pairwise <span class="sc">~</span> Condition, <span class="at">adjust =</span> <span class="st">"bonferroni"</span>) <span class="co"># also works with mod1!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 Condition emmean    SE df lower.CL upper.CL
 1           5.11 0.749 68    3.617     6.60
 2           1.89 0.749 68    0.395     3.38
 3           3.89 0.749 68    2.395     5.38
 4           4.83 0.749 68    3.340     6.33

Confidence level used: 0.95 

$contrasts
 contrast                estimate   SE df t.ratio p.value
 Condition1 - Condition2    3.222 1.06 68   3.044  0.0199
 Condition1 - Condition3    1.222 1.06 68   1.155  1.0000
 Condition1 - Condition4    0.278 1.06 68   0.262  1.0000
 Condition2 - Condition3   -2.000 1.06 68  -1.889  0.3787
 Condition2 - Condition4   -2.944 1.06 68  -2.781  0.0420
 Condition3 - Condition4   -0.944 1.06 68  -0.892  1.0000

P value adjustment: bonferroni method for 6 tests </code></pre>
</div>
</div>
<div class="notes">
<p>Should we adjust for multiple comparisons? It depends. There are good reasons for either.</p>
</div>
</section>
<section id="effect-sizes-power" class="level2">
<h2 class="anchored" data-anchor-id="effect-sizes-power">Effect Sizes &amp; Power</h2>
<p>The most common effect size estimate for an ANOVA is <em>partial eta squared</em> <span class="math inline">\(\eta_p^2\)</span> (as we calculated with <code>afex::aov_ez</code> before). We get <em>one per factor</em> and it summarizes all pairwise effects within it.<br>
We could also calculate Cohen’s d for each pairwise comparison within the factor but this is tedious and gets confusing quickly (1 factor with 5 levels = 10 effects; 3 factors with 5 levels each = 30 effects). It’s still sad that <code>emmeans</code> doesn’t output it as one additional column.</p>
<!--


::: {.cell}

```{.r .cell-code}
library(lsr)

d_1_2 <- cohensD(intrusions ~ Condition, 
                 data = filter(dat, Condition %in% c(1,2)) %>% 
                   droplevels())

d_1_3 <- cohensD(intrusions ~ Condition, 
                 data = filter(dat, Condition %in% c(1,3)) %>%
                   droplevels()) 

# and so forth...

d_1_2
```

::: {.cell-output .cell-output-stdout}

```
[1] 0.9964172
```


:::

```{.r .cell-code}
d_1_3
```

::: {.cell-output .cell-output-stdout}

```
[1] 0.3376282
```


:::
:::


-->
<p>. . .</p>
<p><br>
Effect sizes are important to calculate the <strong>statistical power</strong> of your study before conducting it. Use an estimated effect size based on prior research:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pwr)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pwr.anova.test</span>(<span class="at">k =</span> <span class="dv">4</span>, <span class="at">f =</span> .<span class="dv">4</span>, <span class="at">sig.level =</span> .<span class="dv">05</span>, <span class="at">power =</span> .<span class="dv">8</span>) <span class="co">#we leave out the n parameter to let it be calculated</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Balanced one-way analysis of variance power calculation 

              k = 4
              n = 18.04262
              f = 0.4
      sig.level = 0.05
          power = 0.8

NOTE: n is number in each group</code></pre>
</div>
</div>
</section>
<section id="write-up" class="level2">
<h2 class="anchored" data-anchor-id="write-up">Write Up</h2>
<p>Once again, the <code>apa</code> package helps us here - if we used <code>afex::aov_ez</code> instead of <code>lm</code> 😅:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>mod <span class="sc">%&gt;%</span> apa<span class="sc">::</span><span class="fu">anova_apa</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Effect                                              
1 (Intercept) F(1, 68) = 110.29, p &lt; .001, petasq = .62 ***
2   Condition F(3, 68) =   3.79, p = .014, petasq = .14 *  </code></pre>
</div>
</div>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>mod <span class="sc">%&gt;%</span> <span class="fu">emmeans</span>(<span class="st">"Condition"</span>) <span class="sc">%&gt;%</span> <span class="fu">pairs</span>(<span class="at">adjust=</span><span class="st">"none"</span>) <span class="co">#follow up t-tests without adjustment</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate   SE df t.ratio p.value
 Condition1 - Condition2    3.222 1.06 68   3.044  0.0033
 Condition1 - Condition3    1.222 1.06 68   1.155  0.2523
 Condition1 - Condition4    0.278 1.06 68   0.262  0.7938
 Condition2 - Condition3   -2.000 1.06 68  -1.889  0.0631
 Condition2 - Condition4   -2.944 1.06 68  -2.781  0.0070
 Condition3 - Condition4   -0.944 1.06 68  -0.892  0.3755</code></pre>
</div>
</div>
<p>Looking at contrasts including condition 1 (control group): Only condition 2 different.<br>
Let’s get the associated effect size of this specific contrast:</p>
<p>. . .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohensD</span>(intrusions <span class="sc">~</span> Condition, </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> <span class="fu">filter</span>(dat, Condition <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="sc">%&gt;%</span> <span class="fu">droplevels</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9964172</code></pre>
</div>
</div>
<p>. . .</p>
<blockquote class="blockquote">
<p>There was a significant difference between groups in overall intrusion frequency in daily life, <span class="math inline">\(F(3, 68) = 3.79, p = 0.014, \eta_p^2 = .14\)</span>. Pairwise comparisons demonstrated that relative to the no-task control group, only those in the reactivation-plus-Tetris group, <span class="math inline">\(t(68) = 3.04, p &lt; 0.01, d = 1.00\)</span>, experienced significantly fewer intrusive memories…</p>
</blockquote>
</section>
</section>
<section id="thanks" class="level1">
<h1>Thanks!</h1>
<p>Learning objectives:</p>
<ul>
<li>Be able to run the following tests in R, check their assumptions, and report the results: Chi², <em>t</em>-tests, correlation, and one-way ANOVA</li>
</ul>
<p>Next week:</p>
<ul>
<li>General Linear Model!</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>